name: create-release-on-close
description: Creates a new GitHub release when a pull request is closed
author: Jeremy Escobar
branding:
  icon: activity
  color: gray-dark
inputs:
  release_name: 
    description: "Release version"
    required: false
  body:
    description: "Description of changes"
    required: false
  files:
    description: "List of asset files"
    required: false
  name:
    description: "Custom release name"
    required: false
  tag_name:
    description: "Tag name"
    required: false
  draft:
    description: "Create a draft"
    required: false
  prerelease:
    description: "Identify as prerelease"
    required: false
  repository:
    description: "Repository in <owner>/<repo> format"
    required: false
  token:
    description: "GitHub Personal Access Token"
    required: true
    default: ${{ github.WORKFLOW_SECRET }}
  target_commitish:
    description: "Commitish value"
    required: false
  generate_release_notes:
    description: "Automatically generate name and body"
    required: false
  append_body:
    description: "Append to existing body"
    required: false
env:
  GITHUB_TOKEN:
    description: "GitHub token for creating release"
outputs:
  url:
    description: "Release HTML Page URL"
  id:
    description: "Release ID"
  upload_url:
    description: "URL for uploading assets"
runs:
  using: "node16"
  main: "dist/index.js"

