name: create-release
description: Create Release upon Close Pull Request
author: Jeremy Escobar
branding:
  icon: activity
  color: gray-dark
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Python Action
      runs-on: 
        - self-hosted
        - label-1
      shell: bash
      uses: jge162/create-release@v1.0.4
    - name: Run Action
      runs-on: 
        - self-hosted
        - label-1     
        shell: bash
      run: |
        echo "Hello, world!"
