name: "Create Release upon Close Pull Request"
description: "Streamline releases based on certain conditions"
author: "Jeremy Escobar"
inputs:
  input1:
    description: "An input for the action"
    required: true
outputs:
  output1:
    description: "An output from the action"
runs:
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Run Action"
      run: |
        echo "Hello, world!"
