name: Python Action
description: Quickly run your Python code and verify it is error-free
author: Jeremy Escobar
branding:
  icon: activity
  color: gray-dark
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Python Action
      runs-on: self-hosted
      shell: bash
      uses: jge162/Action-workflows@v0.0.6
    - name: Run Action
      runs-on: self-hosted
      shell: bash
      run: |
        echo "Hello, world!"
