name: create-release-on-close

description: Creates a new GitHub release when a pull request is closed

author: Jeremy Escobar

branding:
  icon: activity
  color: gray-dark

inputs:
  release-notes:
    description: "Notes to include in the release body"
    required: false
  release-notes-path:
    description: "Path to a file containing notes to include in the release body"
    required: false
  release-name:
    description: "A custom name for the release. Defaults to the tag name"
    required: false
  tag-name:
    description: "The tag name to use for the release. Defaults to the GitHub reference"
    required: false
  is-draft:
    description: "Whether to create a draft release. Defaults to false"
    required: false
  is-prerelease:
    description: "Whether to mark the release as a prerelease. Defaults to false"
    required: false
  asset-files:
    description: "A newline-delimited list of path globs for asset files to include in the release"
    required: false
  fail-on-unmatched-files:
    description: "Whether to fail if any of the asset files globs match nothing. Defaults to false"
    required: false
  repository:
    description: "The repository in <owner>/<repo> format to make the release against"
    required: false
  github-token:
    description: "A GitHub Personal Access Token with authorization to create releases"
    required: false
    default: ${{ github.WORKFLOW_SECRET }}
  commitish:
    description: "The commit or branch to use as the base for the release"
    required: false
  discussion-category:
    description: "The name of a discussion category to create and link to the release"
    required: false
  generate-release-notes:
    description: "Whether to automatically generate release notes"
    required: false
  append-release-notes:
    description: "Whether to append release notes to an existing release body. Defaults to false."
    required: false

env:
  GITHUB_TOKEN: "The GitHub Actions token provided by GitHub"

outputs:
  release-url:
    description: "The URL to the release page on GitHub"
  release-id:
    description: "The ID of the newly created release"
  upload-url:
    description: "The URL to use for uploading assets to the release"
  assets:
    description: "A JSON array containing information about each uploaded asset"

runs:
  using: "node16"
  main: "dist/index.js"
