on:
  schedule:
    - cron: '0 12 * * *' # Runs at 12 PM UTC every day
  workflow_dispatch:
  
jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create API directory
        run: mkdir -p ./resources/API

      - name: Create check_api_status.sh script
        run: touch ./resources/API/check_api_status.sh

      - name: Install jq
        run: sudo apt-get install jq

      #- name: Check API Status
      #  run: |
      #    cd ./resources/API
      #    response=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/actions)
      #    status=$(echo $response | jq '.status')
      #    echo "$(date): GitHub Actions API status: $status" >> ../../commitlog.md
      #  env:
      #    TOKEN: ${{ secrets.WORKFLOW_SECRET }}
          
      - name: Check API Status
        run: |
          cd ./resources/API
          response=$(curl -s https://kctbh9vrtdwd.statuspage.io/api/v2/status.json)
          status=$(echo $response | jq -r '.status.indicator')
          echo -e "$(date):\n GitHub Actions API status: $status" >> ../../commitlog.md
        env:
          TOKEN: ${{ secrets.WORKFLOW_SECRET }}


      - name: Commit changes
        run: |
          echo -e "$(date): $(cat commit_message.txt)\n" >> COMMITLOG.md
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "<Jeremy Escobar>"
          git add commitlog.md
          git commit -m "Automated commit: Update API status in commitlog"
          git push
