on:
  schedule:
    - cron: '0 12 * * *' # Runs at 12 PM UTC every day
  workflow_dispatch:

jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create API directory
        run: mkdir -p ./resources/API

      - name: Create check_api_status.sh script
        run: touch ./resources/API/check_api_status.sh

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check API Status
        run: |
          cd ./resources/API
          response=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/actions)
          status=$(echo $response | jq '.status')
          echo "$(date): GitHub Actions API status: $status" >> ../commitlog.md
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "<Your Name>"
          git add commitlog.md
          git commit -m "Automated commit: Update API status in commitlog"
          git push

