name: Python Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install jshint
      run: npm install -g jshint

    - name: Run script
      run: |
        echo "Run, Build Application using scripts"
        python3 -c "
        scripts = ['python_java_tester.py']
        for script in scripts:
            with open(script, 'r') as file:
                exec(file.read())
        "
