# run file to verify it compiles with no errors 
name: Python Action

on:
  schedule:
  - cron: '0 0 * * 6' 
    # action will run once a week on Saturday at 12:00 am 
  workflow_dispatch:

jobs:
  Python-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: |
       echo "Install required dependencies"
       sudo apt-get update
       sudo apt-get install python3
       echo "Install PyGithub module"
       pip3 install PyGithub
      shell: bash

    - run: |
        echo "Build application script outputs Here!"
        python3 -c "
        scripts = [ 'foo.py']
        for script in scripts:
            with open(script, 'r') as file:
                exec(file.read())
        "
    # only run script if I want to check Action 'python_action_checker.py'
    # using dummy placeholder to reduce, api calls
    
