# run file to verify it compiles with no errors 
name: Python Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: jge162/Action-workflows@main

    - run: |
       echo "Install required dependencies"
       sudo apt-get update
       sudo apt-get install python3
       echo "Install PyGithub module"
       pip3 install PyGithub
      shell: bash

    - run: |
        echo "Run, Build Application using scripts"
        python3 -c "
        scripts = ['./python_action_checker.py']
        for script in scripts:
            with open(script, 'r') as file:
                exec(file.read())
        "
