# run file to verify it compiles with no errors 
name: Python Action

on:
  schedule:
  - cron: '0 0,12 * * *' 
    # action will run everyday at 12 am and 12 pm

jobs:
  Python-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: jge162/Action-workflows@main

    - run: |
       echo "Install required dependencies"
       sudo apt-get update
       sudo apt-get install python3
       echo "Install PyGithub module"
       pip3 install PyGithub
      shell: bash

    - run: |
        echo "Build application script outputs Here!"
        python3 -c "
        scripts = [ 'foo.py']
        for script in scripts:
            with open(script, 'r') as file:
                exec(file.read())
        "
    # only run script if I want to check Action 'python_action_checker.py'
    # using dummy placeholder to reduce, api calls
    
